language: python
python:
    - "3.2"  # TODO as in Travis's Ubuntu 12
    - "3.4"  # as in Ubuntu 15.10
addons:
    apt:
        packages:
            - python3-pyqt4
env:
    - PYTHONPATH=/usr/lib/python3/dist-packages
script: ./test.py
